### employee login
POST http://localhost:9000/api/auth/authenticate
Content-Type: application/json

{
  "username": "tuhinal",
  "password": "tuhin123"
}

> {% client.global.set("access_token", response.body.access_token);  %}

###