### employee login
POST http://116.68.206.158:9009/api/v1/authentication/employee/authenticate
Content-Type: application/json

{
  "username": "system-admin-0",
  "password": "123Abc"
}

> {% client.global.set("access_token", response.body.access_token);  %}

###